// Marcas y modelos para los desplegables al dar de alta un coche.
// Puedes editar esta lista: añade, quita o corrige lo que quieras.
// Si una marca o un modelo no está, se puede escribir a mano igualmente.
window.MARCAS = {
  "Abarth": ["500", "595", "695", "124 Spider"],
  "Alfa Romeo": ["146", "147", "156", "159", "166", "Brera", "Giulia", "Giulietta", "GT", "MiTo", "Stelvio", "Tonale", "Spider"],
  "Alpine": ["A110"],
  "Aston Martin": ["DB9", "DB11", "DB12", "DBS", "DBX", "Vantage", "Rapide"],
  "Audi": ["A1", "A2", "A3", "A4", "A4 Allroad", "A5", "A6", "A6 Allroad", "A7", "A8", "Q2", "Q3", "Q4 e-tron", "Q5", "Q7", "Q8", "e-tron", "TT", "R8", "RS3", "RS4", "RS6", "S3", "S4"],
  "Bentley": ["Bentayga", "Continental GT", "Flying Spur"],
  "BMW": ["Serie 1", "Serie 2", "Serie 2 Active Tourer", "Serie 3", "Serie 4", "Serie 5", "Serie 6", "Serie 7", "Serie 8", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "Z4", "i3", "i4", "iX", "iX1", "iX3", "M2", "M3", "M4", "M5"],
  "Bugatti": ["Chiron", "Veyron"],
  "Cadillac": ["ATS", "CTS", "Escalade", "XT4", "XT5"],
  "Chevrolet": ["Aveo", "Camaro", "Captiva", "Cruze", "Kalos", "Lacetti", "Matiz", "Orlando", "Spark", "Trax"],
  "Chrysler": ["300C", "Grand Voyager", "PT Cruiser", "Voyager"],
  "Citroën": ["Berlingo", "C1", "C2", "C3", "C3 Aircross", "C3 Picasso", "C4", "C4 Cactus", "C4 Picasso", "C4 SpaceTourer", "C4 X", "C5", "C5 Aircross", "C5 X", "C6", "C8", "C15", "DS3", "DS4", "DS5", "Jumper", "Jumpy", "Nemo", "Saxo", "Xsara", "Xsara Picasso", "ZX", "ë-C4"],
  "Cupra": ["Ateca", "Born", "Formentor", "León", "Tavascan", "Terramar"],
  "Dacia": ["Dokker", "Duster", "Jogger", "Lodgy", "Logan", "Sandero", "Sandero Stepway", "Spring"],
  "Daewoo": ["Lanos", "Matiz", "Nubira", "Tacuma"],
  "Daihatsu": ["Cuore", "Sirion", "Terios", "Materia"],
  "Dodge": ["Caliber", "Challenger", "Charger", "Journey", "Nitro", "RAM"],
  "DS": ["DS3", "DS3 Crossback", "DS4", "DS7 Crossback", "DS9"],
  "Ferrari": ["296", "458", "488", "812", "California", "F8", "Portofino", "Purosangue", "Roma", "SF90"],
  "Fiat": ["500", "500L", "500X", "600", "Bravo", "Croma", "Doblò", "Ducato", "Fiorino", "Freemont", "Grande Punto", "Idea", "Multipla", "Panda", "Punto", "Qubo", "Scudo", "Sedici", "Seicento", "Stilo", "Tipo", "Ulysse"],
  "Ford": ["B-Max", "C-Max", "EcoSport", "Edge", "Explorer", "Fiesta", "Focus", "Fusion", "Galaxy", "Ka", "Kuga", "Mondeo", "Mustang", "Mustang Mach-E", "Puma", "Ranger", "S-Max", "Tourneo Connect", "Tourneo Custom", "Transit", "Transit Connect", "Transit Custom"],
  "Honda": ["Accord", "City", "Civic", "CR-V", "CR-Z", "e", "FR-V", "HR-V", "Insight", "Jazz", "Legend", "Prelude", "S2000", "ZR-V"],
  "Hummer": ["H2", "H3"],
  "Hyundai": ["Accent", "Atos", "Bayon", "Coupé", "Elantra", "Getz", "i10", "i20", "i30", "i40", "Ioniq", "Ioniq 5", "Ioniq 6", "ix20", "ix35", "Kona", "Matrix", "Santa Fe", "Sonata", "Terracan", "Tucson", "Veloster"],
  "Infiniti": ["Q30", "Q50", "QX30", "QX70"],
  "Isuzu": ["D-Max", "Trooper"],
  "Iveco": ["Daily", "Eurocargo"],
  "Jaguar": ["E-Pace", "F-Pace", "F-Type", "I-Pace", "S-Type", "X-Type", "XE", "XF", "XJ"],
  "Jeep": ["Avenger", "Cherokee", "Compass", "Grand Cherokee", "Patriot", "Renegade", "Wrangler"],
  "Kia": ["Carens", "Carnival", "Ceed", "Cerato", "EV3", "EV6", "EV9", "Niro", "Optima", "Picanto", "Pro_cee'd", "Rio", "Sorento", "Soul", "Sportage", "Stinger", "Stonic", "Venga", "XCeed"],
  "Lada": ["Niva", "Samara"],
  "Lamborghini": ["Aventador", "Gallardo", "Huracán", "Revuelto", "Urus"],
  "Lancia": ["Delta", "Musa", "Phedra", "Thesis", "Ypsilon"],
  "Land Rover": ["Defender", "Discovery", "Discovery Sport", "Freelander", "Range Rover", "Range Rover Evoque", "Range Rover Sport", "Range Rover Velar"],
  "Lexus": ["CT", "ES", "GS", "IS", "LC", "LS", "NX", "RX", "RZ", "UX"],
  "Lotus": ["Elise", "Emira", "Evora", "Exige"],
  "Maserati": ["Ghibli", "GranTurismo", "Grecale", "Levante", "MC20", "Quattroporte"],
  "Maxus": ["Deliver 9", "eDeliver 3", "eDeliver 9", "T90"],
  "Maybach": ["57", "62", "Clase S"],
  "Mazda": ["2", "3", "5", "6", "323", "626", "BT-50", "CX-3", "CX-30", "CX-5", "CX-60", "CX-7", "CX-80", "MX-5", "MX-30", "RX-8", "Premacy", "Tribute"],
  "McLaren": ["540C", "570S", "720S", "Artura", "GT"],
  "Mercedes-Benz": ["Citan", "Clase A", "Clase B", "Clase C", "Clase CLA", "Clase CLK", "Clase CLS", "Clase E", "Clase G", "Clase GLA", "Clase GLB", "Clase GLC", "Clase GLE", "Clase GLK", "Clase GLS", "Clase ML", "Clase R", "Clase S", "Clase SL", "Clase SLK", "Clase V", "EQA", "EQB", "EQC", "EQE", "EQS", "Sprinter", "Vaneo", "Viano", "Vito"],
  "MG": ["3", "4", "5", "HS", "Marvel R", "ZS", "ZR"],
  "Mini": ["Clubman", "Cooper", "Countryman", "Paceman", "One", "Cabrio"],
  "Mitsubishi": ["ASX", "Colt", "Eclipse Cross", "L200", "Lancer", "Montero", "Outlander", "Space Star"],
  "Nissan": ["350Z", "370Z", "Almera", "Ariya", "Cabstar", "Juke", "Leaf", "Micra", "Murano", "Navara", "Note", "NV200", "NV300", "Pathfinder", "Patrol", "Pixo", "Primera", "Pulsar", "Qashqai", "Qashqai+2", "Terrano", "Townstar", "X-Trail"],
  "Opel": ["Adam", "Agila", "Ampera", "Antara", "Astra", "Combo", "Corsa", "Crossland", "Frontera", "Grandland", "Insignia", "Karl", "Meriva", "Mokka", "Movano", "Vectra", "Vivaro", "Zafira"],
  "Peugeot": ["106", "107", "108", "205", "206", "207", "208", "306", "307", "308", "309", "405", "406", "407", "408", "508", "1007", "2008", "3008", "5008", "Bipper", "Boxer", "Expert", "Partner", "RCZ", "Rifter", "Traveller"],
  "Polestar": ["2", "3", "4"],
  "Porsche": ["718 Boxster", "718 Cayman", "911", "Cayenne", "Cayman", "Macan", "Panamera", "Taycan"],
  "Renault": ["Arkana", "Austral", "Captur", "Clio", "Espace", "Fluence", "Grand Scénic", "Kadjar", "Kangoo", "Koleos", "Laguna", "Master", "Mégane", "Mégane E-Tech", "Modus", "Rafale", "Scénic", "Symbioz", "Talisman", "Trafic", "Twingo", "Twizy", "Vel Satis", "Zoe"],
  "Rolls-Royce": ["Cullinan", "Ghost", "Phantom", "Wraith"],
  "Rover": ["25", "45", "75", "200", "400"],
  "Saab": ["9-3", "9-5", "900"],
  "Seat": ["Alhambra", "Altea", "Arona", "Arosa", "Ateca", "Córdoba", "Exeo", "Ibiza", "Ibiza SC", "Inca", "León", "León ST", "Mii", "Tarraco", "Toledo"],
  "Skoda": ["Citigo", "Elroq", "Enyaq", "Fabia", "Kamiq", "Karoq", "Kodiaq", "Octavia", "Rapid", "Roomster", "Scala", "Superb", "Yeti"],
  "Smart": ["Forfour", "Fortwo", "Roadster", "#1", "#3"],
  "SsangYong": ["Actyon", "Korando", "Kyron", "Musso", "Rexton", "Tivoli", "XLV"],
  "Subaru": ["BRZ", "Forester", "Impreza", "Legacy", "Outback", "Solterra", "XV"],
  "Suzuki": ["Across", "Alto", "Baleno", "Celerio", "Grand Vitara", "Ignis", "Jimny", "Liana", "S-Cross", "Splash", "Swace", "Swift", "SX4", "Vitara", "Wagon R"],
  "Tesla": ["Model 3", "Model S", "Model X", "Model Y", "Cybertruck"],
  "Toyota": ["4Runner", "Auris", "Avensis", "Aygo", "Aygo X", "bZ4X", "C-HR", "Camry", "Corolla", "Corolla Cross", "Hilux", "Land Cruiser", "Prius", "Proace", "RAV4", "Supra", "Urban Cruiser", "Verso", "Yaris", "Yaris Cross"],
  "Volkswagen": ["Amarok", "Arteon", "Beetle", "Bora", "Caddy", "California", "Caravelle", "Crafter", "Eos", "Golf", "Golf Plus", "Golf Sportsvan", "ID.3", "ID.4", "ID.5", "ID.7", "ID. Buzz", "Jetta", "Multivan", "New Beetle", "Passat", "Passat CC", "Phaeton", "Polo", "Scirocco", "Sharan", "T-Cross", "T-Roc", "Tiguan", "Touareg", "Touran", "Transporter", "Up!", "Vento"],
  "Volvo": ["C30", "C40", "EX30", "EX90", "S40", "S60", "S80", "S90", "V40", "V50", "V60", "V70", "V90", "XC40", "XC60", "XC70", "XC90"],
};
